server :
    port : 80



spring:
    thymeleaf:
        prefix: /views/
        suffix: .html
        cashe: false

    servlet:
        multipart:
           max-file-size: 10MB
           max-request-size: 10MB
        
